-- Demand-first lead machine: structured marketing, fulfillment and specialist-acquisition data.
-- Apply manually in Supabase SQL editor after deploying the matching application code.
-- Additive migration: existing requests remain valid and new fields are nullable/defaulted.

BEGIN;

ALTER TABLE public.service_requests
  -- Demand taxonomy: keep these as columns (not JSON) so they are easy to filter/export later.
  ADD COLUMN IF NOT EXISTS subcategory_text text NULL,
  ADD COLUMN IF NOT EXISTS requested_service text NULL,
  ADD COLUMN IF NOT EXISTS client_budget_text text NULL,
  ADD COLUMN IF NOT EXISTS preferred_contact_method text NULL,

  -- First-touch attribution details. acquisition_* already stores source/medium/campaign/referrer/landing.
  ADD COLUMN IF NOT EXISTS acquisition_content text NULL,
  ADD COLUMN IF NOT EXISTS acquisition_term text NULL,
  ADD COLUMN IF NOT EXISTS acquisition_gclid text NULL,
  ADD COLUMN IF NOT EXISTS acquisition_fbclid text NULL,

  -- Marketplace liquidity / fulfillment.
  ADD COLUMN IF NOT EXISTS existing_supply_count integer NULL,
  ADD COLUMN IF NOT EXISTS profiles_shown_count integer NULL,
  ADD COLUMN IF NOT EXISTS external_search_required boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS fulfillment_status text NOT NULL DEFAULT 'unassessed',
  ADD COLUMN IF NOT EXISTS matched_specialist_name text NULL,
  ADD COLUMN IF NOT EXISTS matched_specialist_id uuid NULL,
  ADD COLUMN IF NOT EXISTS first_response_at timestamptz NULL,
  ADD COLUMN IF NOT EXISTS matched_at timestamptz NULL,
  ADD COLUMN IF NOT EXISTS closed_at timestamptz NULL,
  ADD COLUMN IF NOT EXISTS loss_reason text NULL,
  ADD COLUMN IF NOT EXISTS fulfillment_notes text NULL,

  -- External supply acquisition generated by this demand signal.
  ADD COLUMN IF NOT EXISTS external_specialist_name text NULL,
  ADD COLUMN IF NOT EXISTS external_specialist_source text NULL,
  ADD COLUMN IF NOT EXISTS external_specialist_contact text NULL,
  ADD COLUMN IF NOT EXISTS specialist_acquisition_status text NOT NULL DEFAULT 'not_started',
  ADD COLUMN IF NOT EXISTS specialist_acquisition_plan text NULL,
  ADD COLUMN IF NOT EXISTS specialist_registered_at timestamptz NULL,
  ADD COLUMN IF NOT EXISTS specialist_became_paid_at timestamptz NULL,
  ADD COLUMN IF NOT EXISTS specialist_acquisition_notes text NULL,

  -- Economics. Store money in integer euro cents to avoid floating point errors.
  ADD COLUMN IF NOT EXISTS attributed_ad_cost_cents integer NULL,
  ADD COLUMN IF NOT EXISTS attributed_revenue_cents integer NULL;

ALTER TABLE public.service_requests
  DROP CONSTRAINT IF EXISTS service_requests_existing_supply_count_non_negative,
  ADD CONSTRAINT service_requests_existing_supply_count_non_negative
    CHECK (existing_supply_count IS NULL OR existing_supply_count >= 0),
  DROP CONSTRAINT IF EXISTS service_requests_profiles_shown_count_non_negative,
  ADD CONSTRAINT service_requests_profiles_shown_count_non_negative
    CHECK (profiles_shown_count IS NULL OR profiles_shown_count >= 0),
  DROP CONSTRAINT IF EXISTS service_requests_attributed_ad_cost_non_negative,
  ADD CONSTRAINT service_requests_attributed_ad_cost_non_negative
    CHECK (attributed_ad_cost_cents IS NULL OR attributed_ad_cost_cents >= 0),
  DROP CONSTRAINT IF EXISTS service_requests_fulfillment_status_check,
  ADD CONSTRAINT service_requests_fulfillment_status_check
    CHECK (fulfillment_status IN (
      'unassessed', 'existing_supply', 'external_search', 'specialist_found',
      'matched', 'fulfilled', 'unfilled'
    )),
  DROP CONSTRAINT IF EXISTS service_requests_specialist_acquisition_status_check,
  ADD CONSTRAINT service_requests_specialist_acquisition_status_check
    CHECK (specialist_acquisition_status IN (
      'not_started', 'prospecting', 'contacted', 'invited',
      'registered', 'paid', 'declined', 'not_needed'
    )),
  DROP CONSTRAINT IF EXISTS service_requests_preferred_contact_method_check,
  ADD CONSTRAINT service_requests_preferred_contact_method_check
    CHECK (
      preferred_contact_method IS NULL OR
      preferred_contact_method IN ('email', 'phone', 'telegram', 'whatsapp', 'any')
    );

CREATE INDEX IF NOT EXISTS idx_service_requests_category_language_created
  ON public.service_requests (category_text, preferred_language, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_service_requests_location_created
  ON public.service_requests (country_code, postal_code, city, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_service_requests_fulfillment_status_created
  ON public.service_requests (fulfillment_status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_service_requests_external_search_created
  ON public.service_requests (external_search_required, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_service_requests_specialist_acquisition_created
  ON public.service_requests (specialist_acquisition_status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_service_requests_acquisition_channel_created
  ON public.service_requests (acquisition_source, acquisition_medium, created_at DESC);

COMMENT ON COLUMN public.service_requests.requested_service IS
  'Normalized human-readable service requested by the client, separate from broad category.';
COMMENT ON COLUMN public.service_requests.existing_supply_count IS
  'Number of matching active Freuly specialists known when the request was assessed.';
COMMENT ON COLUMN public.service_requests.external_search_required IS
  'True when Freuly needs to source a specialist outside the current active marketplace supply.';
COMMENT ON COLUMN public.service_requests.fulfillment_status IS
  'Operational marketplace outcome used for fill-rate and demand-gap analysis.';
COMMENT ON COLUMN public.service_requests.specialist_acquisition_status IS
  'B2B conversion state when a client demand signal is used to recruit an external specialist.';
COMMENT ON COLUMN public.service_requests.attributed_ad_cost_cents IS
  'Optional manually or programmatically attributed acquisition spend for this request, in euro cents.';

COMMIT;
