-- =============================================================================
-- MOVED (read-only pointer)
-- =============================================================================
-- Production RPC baseline diagnostics live with other read-only checks:
--
--   supabase/manual-checks/2026-07-18_geo_rpc_baseline_diagnostics.sql
--
-- This file under manual_migrations is intentionally NOT an executable migration.
-- Do not apply. Do not confuse with:
--   supabase/manual_migrations/2026-07-18_search_specialists_local_radius_v2.sql
-- which remains blocked until the baseline dump is reviewed.
-- =============================================================================
