-- Adds multilingual search terms for the child category "it-support".
-- Target category slug: it-support
-- Languages: ru, uk, de
-- Safe to run multiple times: duplicates are skipped.
-- Important: website route locale may be "ua", but category_search_terms.lang must use "uk".

WITH target_category AS (
  SELECT id
  FROM categories
  WHERE slug = 'it-support'
  LIMIT 1
),
terms(lang, term) AS (
  VALUES
    -- RU: IT / web development / sites
    ('ru', 'it специалист'),
    ('ru', 'it специалисты'),
    ('ru', 'айти специалист'),
    ('ru', 'айти специалисты'),
    ('ru', 'ит специалист'),
    ('ru', 'ит специалисты'),
    ('ru', 'айтишник'),
    ('ru', 'айтишники'),
    ('ru', 'программист'),
    ('ru', 'программисты'),
    ('ru', 'разработчик'),
    ('ru', 'разработчики'),
    ('ru', 'веб разработчик'),
    ('ru', 'веб-разработчик'),
    ('ru', 'web разработчик'),
    ('ru', 'frontend'),
    ('ru', 'front-end'),
    ('ru', 'фронтенд'),
    ('ru', 'backend'),
    ('ru', 'back-end'),
    ('ru', 'бэкенд'),
    ('ru', 'fullstack'),
    ('ru', 'full-stack'),
    ('ru', 'фулстек'),
    ('ru', 'создание сайтов'),
    ('ru', 'разработка сайтов'),
    ('ru', 'сайт под ключ'),
    ('ru', 'сайтподключ'),
    ('ru', 'сделать сайт'),
    ('ru', 'заказать сайт'),
    ('ru', 'сайт для бизнеса'),
    ('ru', 'создание сайта в германии'),
    ('ru', 'разработка сайта в германии'),
    ('ru', 'создание сайтов в германии'),
    ('ru', 'создание сайтов в европе'),
    ('ru', 'разработка сайтов в европе'),
    ('ru', 'сайт на wordpress'),
    ('ru', 'wordpress'),
    ('ru', 'вордпресс'),
    ('ru', 'wordpress сайт'),
    ('ru', 'сайт на вордпресс'),
    ('ru', 'shopify'),
    ('ru', 'шопифай'),
    ('ru', 'shopify магазин'),
    ('ru', 'магазин на shopify'),
    ('ru', 'интернет магазин'),
    ('ru', 'интернет-магазин'),
    ('ru', 'создание интернет магазина'),
    ('ru', 'разработка интернет магазина'),
    ('ru', 'онлайн магазин'),
    ('ru', 'ecommerce'),
    ('ru', 'e-commerce'),
    ('ru', 'лендинг'),
    ('ru', 'landing'),
    ('ru', 'landing page'),
    ('ru', 'посадочная страница'),
    ('ru', 'корпоративный сайт'),
    ('ru', 'сайт компании'),
    ('ru', 'сайт портфолио'),
    ('ru', 'портфолио сайт'),
    ('ru', 'техническая поддержка сайта'),
    ('ru', 'доработка сайта'),
    ('ru', 'обслуживание сайта'),
    ('ru', 'поддержка сайта'),
    ('ru', 'расширение функционала сайта'),
    ('ru', 'модернизация сайта'),
    ('ru', 'редизайн сайта'),

    -- RU: SEO / ads / Google / digital marketing
    ('ru', 'seo'),
    ('ru', 'сео'),
    ('ru', 'seo продвижение'),
    ('ru', 'сео продвижение'),
    ('ru', 'seo оптимизация'),
    ('ru', 'сео оптимизация'),
    ('ru', 'seo оптимизация сайта'),
    ('ru', 'продвижение сайтов'),
    ('ru', 'продвижение сайта'),
    ('ru', 'продвижение в google'),
    ('ru', 'продвижение в гугл'),
    ('ru', 'google продвижение'),
    ('ru', 'гугл продвижение'),
    ('ru', 'google ads'),
    ('ru', 'google adwords'),
    ('ru', 'гугл реклама'),
    ('ru', 'реклама в google'),
    ('ru', 'реклама в гугл'),
    ('ru', 'контекстная реклама'),
    ('ru', 'таргетированная реклама'),
    ('ru', 'настройка рекламы'),
    ('ru', 'настройка google ads'),
    ('ru', 'google maps'),
    ('ru', 'гугл карты'),
    ('ru', 'google business profile'),
    ('ru', 'google my business'),
    ('ru', 'профиль компании google'),
    ('ru', 'локальное seo'),
    ('ru', 'локальное сео'),
    ('ru', 'local seo'),
    ('ru', 'geo продвижение'),
    ('ru', 'гео продвижение'),
    ('ru', 'продвижение в google maps'),
    ('ru', 'продвижение в гугл картах'),
    ('ru', 'оформление соцсетей'),
    ('ru', 'ведение соцсетей'),
    ('ru', 'социальные сети для бизнеса'),
    ('ru', 'smm'),
    ('ru', 'смм'),
    ('ru', 'digital маркетинг'),
    ('ru', 'диджитал маркетинг'),
    ('ru', 'интернет маркетинг'),

    -- RU: design / branding / marketplace design
    ('ru', 'веб дизайн'),
    ('ru', 'веб-дизайн'),
    ('ru', 'web design'),
    ('ru', 'дизайн сайта'),
    ('ru', 'дизайн сайтов'),
    ('ru', 'ui дизайн'),
    ('ru', 'ux дизайн'),
    ('ru', 'ui ux'),
    ('ru', 'ui/ux'),
    ('ru', 'логотип'),
    ('ru', 'разработка логотипа'),
    ('ru', 'дизайн логотипа'),
    ('ru', 'фирменный стиль'),
    ('ru', 'брендинг'),
    ('ru', 'брендбук'),
    ('ru', 'brandbook'),
    ('ru', 'графический дизайн'),
    ('ru', 'дизайн полиграфии'),
    ('ru', 'дизайн визиток'),
    ('ru', 'дизайн меню'),
    ('ru', 'дизайн флаеров'),
    ('ru', 'дизайн каталогов'),
    ('ru', 'дизайн баннеров'),
    ('ru', 'дизайн для маркетплейсов'),
    ('ru', 'дизайн для amazon'),
    ('ru', 'amazon дизайн'),
    ('ru', 'маркетплейс'),
    ('ru', 'маркетплейсы'),
    ('ru', 'дизайн карточек товара'),
    ('ru', 'карточки товара amazon'),
    ('ru', 'макет книги'),
    ('ru', 'макеты книг'),
    ('ru', 'макет настольной игры'),
    ('ru', 'макеты настольных игр'),
    ('ru', 'бизнес презентация'),
    ('ru', 'презентация для бизнеса'),
    ('ru', 'презентация для компании'),
    ('ru', 'презентация для стартапа'),
    ('ru', '3d визуализация'),
    ('ru', '3д визуализация'),
    ('ru', 'визуализация интерьера'),
    ('ru', 'визуализация экстерьера'),

    -- UK: IT / web development / sites
    ('uk', 'it спеціаліст'),
    ('uk', 'it спеціалісти'),
    ('uk', 'айті спеціаліст'),
    ('uk', 'айті спеціалісти'),
    ('uk', 'іт спеціаліст'),
    ('uk', 'іт спеціалісти'),
    ('uk', 'айтішник'),
    ('uk', 'айтішники'),
    ('uk', 'програміст'),
    ('uk', 'програмісти'),
    ('uk', 'розробник'),
    ('uk', 'розробники'),
    ('uk', 'веб розробник'),
    ('uk', 'веб-розробник'),
    ('uk', 'web розробник'),
    ('uk', 'frontend'),
    ('uk', 'front-end'),
    ('uk', 'фронтенд'),
    ('uk', 'backend'),
    ('uk', 'back-end'),
    ('uk', 'бекенд'),
    ('uk', 'fullstack'),
    ('uk', 'full-stack'),
    ('uk', 'фулстек'),
    ('uk', 'створення сайтів'),
    ('uk', 'розробка сайтів'),
    ('uk', 'сайт під ключ'),
    ('uk', 'зробити сайт'),
    ('uk', 'замовити сайт'),
    ('uk', 'сайт для бізнесу'),
    ('uk', 'створення сайту в німеччині'),
    ('uk', 'розробка сайту в німеччині'),
    ('uk', 'створення сайтів у німеччині'),
    ('uk', 'створення сайтів в німеччині'),
    ('uk', 'створення сайтів у європі'),
    ('uk', 'розробка сайтів у європі'),
    ('uk', 'сайт на wordpress'),
    ('uk', 'wordpress'),
    ('uk', 'вордпрес'),
    ('uk', 'wordpress сайт'),
    ('uk', 'сайт на вордпрес'),
    ('uk', 'shopify'),
    ('uk', 'шопіфай'),
    ('uk', 'shopify магазин'),
    ('uk', 'магазин на shopify'),
    ('uk', 'інтернет магазин'),
    ('uk', 'інтернет-магазин'),
    ('uk', 'створення інтернет магазину'),
    ('uk', 'розробка інтернет магазину'),
    ('uk', 'онлайн магазин'),
    ('uk', 'ecommerce'),
    ('uk', 'e-commerce'),
    ('uk', 'лендінг'),
    ('uk', 'landing'),
    ('uk', 'landing page'),
    ('uk', 'посадкова сторінка'),
    ('uk', 'корпоративний сайт'),
    ('uk', 'сайт компанії'),
    ('uk', 'сайт портфоліо'),
    ('uk', 'портфоліо сайт'),
    ('uk', 'технічна підтримка сайту'),
    ('uk', 'доопрацювання сайту'),
    ('uk', 'обслуговування сайту'),
    ('uk', 'підтримка сайту'),
    ('uk', 'розширення функціоналу сайту'),
    ('uk', 'модернізація сайту'),
    ('uk', 'редизайн сайту'),

    -- UK: SEO / ads / Google / digital marketing
    ('uk', 'seo'),
    ('uk', 'сео'),
    ('uk', 'seo просування'),
    ('uk', 'сео просування'),
    ('uk', 'seo оптимізація'),
    ('uk', 'сео оптимізація'),
    ('uk', 'seo оптимізація сайту'),
    ('uk', 'просування сайтів'),
    ('uk', 'просування сайту'),
    ('uk', 'просування в google'),
    ('uk', 'просування у google'),
    ('uk', 'просування в гугл'),
    ('uk', 'google просування'),
    ('uk', 'гугл просування'),
    ('uk', 'google ads'),
    ('uk', 'google adwords'),
    ('uk', 'гугл реклама'),
    ('uk', 'реклама в google'),
    ('uk', 'реклама у google'),
    ('uk', 'реклама в гугл'),
    ('uk', 'контекстна реклама'),
    ('uk', 'таргетована реклама'),
    ('uk', 'налаштування реклами'),
    ('uk', 'налаштування google ads'),
    ('uk', 'google maps'),
    ('uk', 'гугл карти'),
    ('uk', 'google business profile'),
    ('uk', 'google my business'),
    ('uk', 'профіль компанії google'),
    ('uk', 'локальне seo'),
    ('uk', 'локальне сео'),
    ('uk', 'local seo'),
    ('uk', 'geo просування'),
    ('uk', 'гео просування'),
    ('uk', 'просування в google maps'),
    ('uk', 'просування у google maps'),
    ('uk', 'просування в гугл картах'),
    ('uk', 'оформлення соцмереж'),
    ('uk', 'ведення соцмереж'),
    ('uk', 'соціальні мережі для бізнесу'),
    ('uk', 'smm'),
    ('uk', 'смм'),
    ('uk', 'digital маркетинг'),
    ('uk', 'діджитал маркетинг'),
    ('uk', 'інтернет маркетинг'),

    -- UK: design / branding / marketplace design
    ('uk', 'веб дизайн'),
    ('uk', 'веб-дизайн'),
    ('uk', 'web design'),
    ('uk', 'дизайн сайту'),
    ('uk', 'дизайн сайтів'),
    ('uk', 'ui дизайн'),
    ('uk', 'ux дизайн'),
    ('uk', 'ui ux'),
    ('uk', 'ui/ux'),
    ('uk', 'логотип'),
    ('uk', 'розробка логотипу'),
    ('uk', 'дизайн логотипу'),
    ('uk', 'фірмовий стиль'),
    ('uk', 'брендинг'),
    ('uk', 'брендбук'),
    ('uk', 'brandbook'),
    ('uk', 'графічний дизайн'),
    ('uk', 'дизайн поліграфії'),
    ('uk', 'дизайн візиток'),
    ('uk', 'дизайн меню'),
    ('uk', 'дизайн флаєрів'),
    ('uk', 'дизайн каталогів'),
    ('uk', 'дизайн банерів'),
    ('uk', 'дизайн для маркетплейсів'),
    ('uk', 'дизайн для amazon'),
    ('uk', 'amazon дизайн'),
    ('uk', 'маркетплейс'),
    ('uk', 'маркетплейси'),
    ('uk', 'дизайн карток товару'),
    ('uk', 'картки товару amazon'),
    ('uk', 'макет книги'),
    ('uk', 'макети книг'),
    ('uk', 'макет настільної гри'),
    ('uk', 'макети настільних ігор'),
    ('uk', 'бізнес презентація'),
    ('uk', 'презентація для бізнесу'),
    ('uk', 'презентація для компанії'),
    ('uk', 'презентація для стартапу'),
    ('uk', '3d візуалізація'),
    ('uk', '3д візуалізація'),
    ('uk', 'візуалізація інтер’єру'),
    ('uk', 'візуалізація інтер''єру'),
    ('uk', 'візуалізація екстер’єру'),
    ('uk', 'візуалізація екстер''єру'),

    -- DE: IT / web development / sites
    ('de', 'it spezialist'),
    ('de', 'it spezialisten'),
    ('de', 'it experte'),
    ('de', 'it experten'),
    ('de', 'it dienstleistungen'),
    ('de', 'it service'),
    ('de', 'it support'),
    ('de', 'programmierer'),
    ('de', 'entwickler'),
    ('de', 'webentwickler'),
    ('de', 'web-entwickler'),
    ('de', 'web developer'),
    ('de', 'frontend entwickler'),
    ('de', 'front-end entwickler'),
    ('de', 'backend entwickler'),
    ('de', 'back-end entwickler'),
    ('de', 'fullstack entwickler'),
    ('de', 'full-stack entwickler'),
    ('de', 'website erstellen'),
    ('de', 'webseite erstellen'),
    ('de', 'website entwicklung'),
    ('de', 'webseiten entwicklung'),
    ('de', 'webentwicklung'),
    ('de', 'homepage erstellen'),
    ('de', 'internetseite erstellen'),
    ('de', 'website für unternehmen'),
    ('de', 'website für firma'),
    ('de', 'website in deutschland erstellen'),
    ('de', 'webseite in deutschland erstellen'),
    ('de', 'website in europa erstellen'),
    ('de', 'wordpress'),
    ('de', 'wordpress website'),
    ('de', 'wordpress seite'),
    ('de', 'wordpress homepage'),
    ('de', 'shopify'),
    ('de', 'shopify shop'),
    ('de', 'shopify store'),
    ('de', 'online shop'),
    ('de', 'onlineshop'),
    ('de', 'online-shop'),
    ('de', 'e commerce'),
    ('de', 'e-commerce'),
    ('de', 'ecommerce'),
    ('de', 'landing page'),
    ('de', 'landingpage'),
    ('de', 'unternehmenswebsite'),
    ('de', 'firmenwebsite'),
    ('de', 'portfolio website'),
    ('de', 'portfolio webseite'),
    ('de', 'website support'),
    ('de', 'website betreuung'),
    ('de', 'website wartung'),
    ('de', 'technischer support'),
    ('de', 'website pflege'),
    ('de', 'website überarbeitung'),
    ('de', 'website redesign'),

    -- DE: SEO / ads / Google / digital marketing
    ('de', 'seo'),
    ('de', 'seo optimierung'),
    ('de', 'suchmaschinenoptimierung'),
    ('de', 'seo agentur'),
    ('de', 'seo für google'),
    ('de', 'google optimierung'),
    ('de', 'google ranking'),
    ('de', 'website ranking'),
    ('de', 'google ads'),
    ('de', 'google adwords'),
    ('de', 'google werbung'),
    ('de', 'werbung bei google'),
    ('de', 'online werbung'),
    ('de', 'internetwerbung'),
    ('de', 'targeting werbung'),
    ('de', 'anzeigen schalten'),
    ('de', 'google ads einrichten'),
    ('de', 'google maps'),
    ('de', 'google business profile'),
    ('de', 'google my business'),
    ('de', 'unternehmensprofil google'),
    ('de', 'lokales seo'),
    ('de', 'local seo'),
    ('de', 'geo marketing'),
    ('de', 'google maps optimierung'),
    ('de', 'google maps ranking'),
    ('de', 'social media betreuung'),
    ('de', 'social media design'),
    ('de', 'social media marketing'),
    ('de', 'smm'),
    ('de', 'digital marketing'),
    ('de', 'online marketing'),
    ('de', 'internet marketing'),

    -- DE: design / branding / marketplace design
    ('de', 'webdesign'),
    ('de', 'web design'),
    ('de', 'website design'),
    ('de', 'webseitendesign'),
    ('de', 'ui design'),
    ('de', 'ux design'),
    ('de', 'ui ux'),
    ('de', 'ui/ux'),
    ('de', 'logo design'),
    ('de', 'logo erstellen'),
    ('de', 'logodesign'),
    ('de', 'corporate design'),
    ('de', 'branding'),
    ('de', 'brandbook'),
    ('de', 'markenbuch'),
    ('de', 'grafikdesign'),
    ('de', 'grafik design'),
    ('de', 'printdesign'),
    ('de', 'flyer design'),
    ('de', 'visitenkarten design'),
    ('de', 'menü design'),
    ('de', 'katalog design'),
    ('de', 'banner design'),
    ('de', 'design für amazon'),
    ('de', 'amazon design'),
    ('de', 'marketplace design'),
    ('de', 'marktplatz design'),
    ('de', 'produktbilder design'),
    ('de', 'produktkarten design'),
    ('de', 'buchlayout'),
    ('de', 'buch layout'),
    ('de', 'brettspiel layout'),
    ('de', 'geschäftspräsentation'),
    ('de', 'business präsentation'),
    ('de', 'unternehmenspräsentation'),
    ('de', 'startup präsentation'),
    ('de', '3d visualisierung'),
    ('de', '3d visualisierung innenraum'),
    ('de', '3d visualisierung außenbereich'),
    ('de', 'innenraum visualisierung'),
    ('de', 'außenbereich visualisierung')
)
INSERT INTO category_search_terms (category_id, lang, term, is_active)
SELECT
  target_category.id,
  terms.lang,
  terms.term,
  true
FROM target_category
CROSS JOIN terms
WHERE NOT EXISTS (
  SELECT 1
  FROM category_search_terms existing
  WHERE existing.category_id = target_category.id
    AND existing.lang = terms.lang
    AND lower(existing.term) = lower(terms.term)
);
