export const UNTRUSTED_CHECKOUT_BODY_KEYS = [
  "specialist_id",
  "specialistId",
  "price_id",
  "priceId",
  "stripe_price_id",
  "amount",
  "currency",
  "user_id",
  "userId",
  "customer_id",
  "customerId",
  "success_url",
  "successUrl",
  "cancel_url",
  "cancelUrl",
  "redirect_url",
  "redirectUrl",
  "return_url",
  "returnUrl",
  "return_uri",
  "returnUri",
  "deep_link",
  "deepLink",
  "app_url",
  "appUrl",
  "checkout_url",
  "checkoutUrl",
  "product_id",
  "productId",
  "credit_id",
  "creditId",
  "promoted_credit_id",
  "promotedCreditId",
  "discount",
  "discount_amount",
  "discountAmount",
  "coupon_id",
  "couponId",
  "coupon",
  "promotion_code",
  "promotionCode",
  "payment_id",
  "paymentId",
  "billing_interval",
  "billingInterval",
  "provider",
  "mode",
] as const;

export function findUntrustedCheckoutBodyKeys(body: Record<string, unknown>): string[] {
  return UNTRUSTED_CHECKOUT_BODY_KEYS.filter((key) => key in body);
}
