"use client";

import { useEffect, useRef, useState, useTransition } from "react";
import type { PromotionLocale } from "@/lib/serviceRequests/promotionConstants";
import type { ServiceRequestPromotionAdmin } from "@/lib/serviceRequests/promotionAdminData";
import { isPromotionLocale } from "@/lib/serviceRequests/localizedPublicCopy";
import {
  closePromotionAction,
  generatePromotionDraftAction,
  publishPromotionAction,
  savePromotionDraftAction,
} from "./promotionActions";

type Props = {
  serviceRequestId: string;
  initialPromotion: ServiceRequestPromotionAdmin | null;
  defaultLocale: string;
};

const LOCALE_LABELS: Record<PromotionLocale, string> = {
  ru: "Русский (RU)",
  ua: "Українська (UA)",
  de: "Deutsch (DE)",
};

function sourceLocaleFrom(value: string | null | undefined): PromotionLocale {
  const normalized = (value ?? "").trim().toLowerCase();
  if (normalized === "uk" || normalized === "ua") return "ua";
  if (isPromotionLocale(normalized)) return normalized;
  return "ru";
}

function sourceCopyFromPromotion(
  promotion: ServiceRequestPromotionAdmin | null,
  sourceLocale: PromotionLocale,
): { title: string; summary: string } {
  return {
    title:
      promotion?.localized_copy?.[sourceLocale]?.title ??
      promotion?.public_title ??
      "",
    summary:
      promotion?.localized_copy?.[sourceLocale]?.summary ??
      promotion?.public_summary ??
      "",
  };
}

function actionErrorMessage(code: string): string {
  if (code === "generation_failed") {
    return "Не удалось сгенерировать промо-текст. Поля можно заполнить вручную или повторить генерацию.";
  }
  if (code === "translation_failed") {
    return "Не удалось создать все переводы. Публикация не выпущена — повторите попытку.";
  }
  if (code === "invalid_input") return "Проверьте заголовок и описание.";
  if (code === "not_found") return "Заявка не найдена.";
  if (code === "unauthorized") return "Сессия администратора недействительна.";
  return "Не удалось выполнить действие.";
}

export default function ServiceRequestPromotionBlock({
  serviceRequestId,
  initialPromotion,
  defaultLocale,
}: Props) {
  const initialSource = sourceLocaleFrom(initialPromotion?.locale ?? defaultLocale);
  const initialCopy = sourceCopyFromPromotion(initialPromotion, initialSource);

  const [promotion, setPromotion] = useState<ServiceRequestPromotionAdmin | null>(initialPromotion);
  const [sourceLocale, setSourceLocale] = useState<PromotionLocale>(initialSource);
  const [title, setTitle] = useState(initialCopy.title);
  const [summary, setSummary] = useState(initialCopy.summary);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [copiedAccept, setCopiedAccept] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isPending, startTransition] = useTransition();
  const autoGeneratedForRequest = useRef<string | null>(null);

  async function generateDraft() {
    setError(null);
    setIsGenerating(true);
    const result = await generatePromotionDraftAction(serviceRequestId);

    if (autoGeneratedForRequest.current !== serviceRequestId) return;

    if (!result.ok) {
      setError(actionErrorMessage(result.error));
      setIsGenerating(false);
      return;
    }

    setSourceLocale(result.draft.locale);
    setTitle(result.draft.title);
    setSummary(result.draft.summary);
    setIsGenerating(false);
  }

  useEffect(() => {
    const nextSource = sourceLocaleFrom(initialPromotion?.locale ?? defaultLocale);
    const nextCopy = sourceCopyFromPromotion(initialPromotion, nextSource);

    setPromotion(initialPromotion);
    setSourceLocale(nextSource);
    setTitle(nextCopy.title);
    setSummary(nextCopy.summary);
    setError(null);

    if (initialPromotion) {
      autoGeneratedForRequest.current = serviceRequestId;
      return;
    }

    if (autoGeneratedForRequest.current === serviceRequestId) return;
    autoGeneratedForRequest.current = serviceRequestId;
    void generateDraft();
  }, [initialPromotion, defaultLocale, serviceRequestId]);

  function draftPayload() {
    return {
      locale: sourceLocale,
      public_title: title,
      public_summary: summary,
    };
  }

  function applyPromotion(next: ServiceRequestPromotionAdmin) {
    setPromotion(next);
    const nextSource = sourceLocaleFrom(next.locale);
    const nextCopy = sourceCopyFromPromotion(next, nextSource);
    setSourceLocale(nextSource);
    setTitle(nextCopy.title);
    setSummary(nextCopy.summary);
  }

  function runAction(
    action: () => Promise<{
      ok: boolean;
      promotion?: ServiceRequestPromotionAdmin;
      error?: string;
    }>,
  ) {
    setError(null);
    setCopied(false);
    setCopiedAccept(false);

    startTransition(async () => {
      const result = await action();
      if (!result.ok || !result.promotion) {
        setError(actionErrorMessage(result.error ?? "server_error"));
        return;
      }
      applyPromotion(result.promotion);
    });
  }

  async function handleRegenerate() {
    autoGeneratedForRequest.current = serviceRequestId;
    await generateDraft();
  }

  async function handleCopyAcceptLink() {
    if (!promotion?.accept_url) return;
    try {
      await navigator.clipboard.writeText(promotion.accept_url);
      setCopiedAccept(true);
    } catch {
      setError("Не удалось скопировать ссылку.");
    }
  }

  async function handleCopyLink() {
    if (!promotion?.public_url) return;
    try {
      await navigator.clipboard.writeText(promotion.public_url);
      setCopied(true);
    } catch {
      setError("Не удалось скопировать ссылку.");
    }
  }

  const isClosed = promotion?.status === "closed";
  const isPublished = promotion?.status === "published";
  const canSubmit = Boolean(title.trim() && summary.trim()) && !isGenerating && !isPending && !isClosed;
  const statusLabel =
    promotion?.status === "draft"
      ? "Черновик"
      : promotion?.status === "published"
        ? "Опубликовано во всех языковых версиях"
        : promotion?.status === "closed"
          ? "Закрыто"
          : "Новый промо-черновик";

  return (
    <section className="mt-6 border-t pt-4 space-y-3">
      <h3 className="font-semibold text-base">Публичная публикация</h3>
      <p className="text-xs text-gray-500">
        Freuly автоматически готовит обезличенный промо-текст по заявке. Проверьте его и при необходимости
        отредактируйте. При публикации украинская, русская и немецкая версии создаются автоматически.
      </p>

      <p className="text-xs text-gray-600">
        Исходный язык заявки:{" "}
        <span className="font-medium">{LOCALE_LABELS[sourceLocale]}</span>
      </p>

      <p className="text-xs text-gray-600">
        Статус: <span className="font-medium">{statusLabel}</span>
      </p>

      {isGenerating ? (
        <p className="rounded border border-blue-100 bg-blue-50 px-3 py-2 text-sm text-blue-800">
          Генерируем промо-текст по заявке…
        </p>
      ) : null}

      <fieldset className="space-y-2 rounded border border-gray-200 p-3">
        <legend className="px-1 text-sm font-medium">
          Публичный текст — {LOCALE_LABELS[sourceLocale]}
        </legend>

        <label className="block">
          <span className="font-medium">Публичный заголовок</span>
          <input
            type="text"
            className="mt-1 block w-full border rounded px-2 py-1"
            value={title}
            disabled={isPending || isClosed || isGenerating}
            onChange={(e) => setTitle(e.target.value)}
          />
        </label>

        <label className="block">
          <span className="font-medium">Публичное описание</span>
          <textarea
            className="mt-1 block w-full border rounded px-2 py-1 min-h-[96px]"
            value={summary}
            disabled={isPending || isClosed || isGenerating}
            onChange={(e) => setSummary(e.target.value)}
          />
        </label>
      </fieldset>

      {error ? <p className="text-red-600 text-sm">{error}</p> : null}

      <div className="flex flex-wrap gap-2 pt-1">
        {!isClosed ? (
          <button
            type="button"
            className="px-3 py-1.5 text-sm rounded border disabled:opacity-50"
            disabled={isPending || isGenerating}
            onClick={handleRegenerate}
          >
            Сгенерировать заново
          </button>
        ) : null}

        {!isClosed ? (
          <button
            type="button"
            className="px-3 py-1.5 text-sm rounded border disabled:opacity-50"
            disabled={!canSubmit}
            onClick={() =>
              runAction(() => savePromotionDraftAction(serviceRequestId, draftPayload()))
            }
          >
            Сохранить черновик
          </button>
        ) : null}

        {!isClosed ? (
          <button
            type="button"
            className="px-3 py-1.5 text-sm rounded bg-blue-700 text-white disabled:opacity-50"
            disabled={!canSubmit}
            onClick={() =>
              runAction(async () => {
                const saved = await savePromotionDraftAction(serviceRequestId, draftPayload());
                if (!saved.ok) return saved;
                return publishPromotionAction(serviceRequestId);
              })
            }
          >
            Опубликовать
          </button>
        ) : null}

        {promotion && !isClosed ? (
          <button
            type="button"
            className="px-3 py-1.5 text-sm rounded border border-red-300 text-red-700 disabled:opacity-50"
            disabled={isPending || isGenerating}
            onClick={() => runAction(() => closePromotionAction(serviceRequestId))}
          >
            Закрыть публикацию
          </button>
        ) : null}

        {promotion && isPublished ? (
          <>
            {promotion.public_url ? (
              <button
                type="button"
                className="px-3 py-1.5 text-sm rounded border disabled:opacity-50"
                disabled={isPending}
                onClick={handleCopyLink}
              >
                {copied ? "Ссылка скопирована" : "Скопировать публичную ссылку"}
              </button>
            ) : null}

            {promotion.accept_url ? (
              <button
                type="button"
                className="px-3 py-1.5 text-sm rounded border border-emerald-300 text-emerald-800 disabled:opacity-50"
                disabled={isPending}
                onClick={handleCopyAcceptLink}
              >
                {copiedAccept ? "Ссылка «Принять» скопирована" : "Скопировать ссылку «Принять заявку»"}
              </button>
            ) : null}
          </>
        ) : null}
      </div>

      <p className="text-xs text-gray-500">
        При публикации система заново создаёт переводы RU / UA / DE из текущего исходного текста.
      </p>

      {isPublished && promotion?.public_urls ? (
        <div className="text-xs text-gray-600 break-all space-y-1">
          <p>
            <strong>RU:</strong> {promotion.public_urls.ru}
          </p>
          <p>
            <strong>UA:</strong> {promotion.public_urls.ua}
          </p>
          <p>
            <strong>DE:</strong> {promotion.public_urls.de}
          </p>
          {promotion.accept_url ? (
            <p>
              <strong>Ссылка «Принять заявку» (для рекламы / Telegram):</strong>{" "}
              {promotion.accept_url}
            </p>
          ) : null}
        </div>
      ) : null}
    </section>
  );
}
